"""Approved v0.9.5-D frontend API-surface contract (generated).

This file is the version-controlled, approved endpoint/client/feature
classification contract. It is generated deterministically by
verification/v0.9.5-d/build_contract.py from the measured API surface
and is validated against the live runtime by tests/test_v095d_api_contract.py.
"""

from __future__ import annotations

ENDPOINT_CLASSIFICATION: dict[tuple[str, str], str] = {
    ('GET', '/api/v1/admin/algorithms'): 'C',
    ('GET', '/api/v1/admin/configurations'): 'A',
    ('GET', '/api/v1/admin/metrics'): 'C',
    ('GET', '/api/v1/admin/registries'): 'B',
    ('GET', '/api/v1/calf/analysis-units'): 'C',
    ('GET', '/api/v1/calf/constructs'): 'B',
    ('GET', '/api/v1/calf/metrics'): 'B',
    ('GET', '/api/v1/calf/metrics/{metric_id}'): 'C',
    ('GET', '/api/v1/exercises/{exercise_id}/attempts'): 'A',
    ('GET', '/api/v1/practice-targets/{practice_target_id}/exercises'): 'A',
    ('GET', '/api/v1/research/data-quality'): 'A',
    ('GET', '/api/v1/research/export/history'): 'A',
    ('GET', '/api/v1/research/export/schema'): 'B',
    ('GET', '/api/v1/research/export/{export_id}'): 'C',
    ('GET', '/api/v1/research/export/{export_id}/manifest'): 'B',
    ('GET', '/api/v1/research/reviews'): 'B',
    ('GET', '/api/v1/revisions/{revision_group_id}'): 'B',
    ('GET', '/api/v1/revisions/{revision_group_id}/comparison'): 'B',
    ('GET', '/api/v1/revisions/{revision_group_id}/trajectory'): 'B',
    ('GET', '/api/v1/students/{student_id}'): 'C',
    ('GET', '/api/v1/students/{student_id}/calf-trajectories'): 'C',
    ('GET', '/api/v1/students/{student_id}/dashboard'): 'B',
    ('GET', '/api/v1/students/{student_id}/engagement-traces'): 'A',
    ('GET', '/api/v1/students/{student_id}/history'): 'C',
    ('GET', '/api/v1/students/{student_id}/journey'): 'A',
    ('GET', '/api/v1/students/{student_id}/learner-model'): 'B',
    ('GET', '/api/v1/students/{student_id}/learner-model/diagnostic-trajectories'): 'C',
    ('GET', '/api/v1/students/{student_id}/learner-model/history-evidence'): 'C',
    ('GET', '/api/v1/students/{student_id}/learner-model/learning-targets'): 'C',
    ('GET', '/api/v1/students/{student_id}/learner-model/metric-trajectories'): 'C',
    ('GET', '/api/v1/students/{student_id}/learner-model/snapshots'): 'B',
    ('GET', '/api/v1/students/{student_id}/learner-model/snapshots/{snapshot_id}'): 'B',
    ('GET', '/api/v1/students/{student_id}/learner-model/task-clusters'): 'C',
    ('GET', '/api/v1/students/{student_id}/practice-targets'): 'A',
    ('GET', '/api/v1/students/{student_id}/practice-targets/{practice_target_id}/context'): 'A',
    ('GET', '/api/v1/students/{student_id}/profile'): 'C',
    ('GET', '/api/v1/students/{student_id}/progress'): 'C',
    ('GET', '/api/v1/students/{student_id}/revision-candidates'): 'A',
    ('GET', '/api/v1/students/{student_id}/transfer-evidence'): 'A',
    ('GET', '/api/v1/submissions/{submission_id}'): 'A',
    ('GET', '/api/v1/submissions/{submission_id}/analyses'): 'A',
    ('GET', '/api/v1/submissions/{submission_id}/analysis-units'): 'C',
    ('GET', '/api/v1/submissions/{submission_id}/calf'): 'B',
    ('GET', '/api/v1/submissions/{submission_id}/diagnostic-audit'): 'A',
    ('GET', '/api/v1/submissions/{submission_id}/error-annotations'): 'C',
    ('GET', '/api/v1/submissions/{submission_id}/pii-candidates'): 'A',
    ('GET', '/api/v1/submissions/{submission_id}/revision-analysis'): 'B',
    ('GET', '/api/v1/submissions/{submission_id}/revision-candidates'): 'B',
    ('GET', '/api/v1/submissions/{submission_id}/syntactic-units'): 'C',
    ('GET', '/api/v1/system/health'): 'A',
    ('GET', '/api/v1/system/live'): 'B',
    ('GET', '/api/v1/system/ready'): 'B',
    ('GET', '/api/v1/system/version'): 'C',
    ('GET', '/docs'): 'C',
    ('GET', '/docs/oauth2-redirect'): 'C',
    ('GET', '/openapi.json'): 'C',
    ('GET', '/redoc'): 'C',
    ('POST', '/api/v1/admin/configurations'): 'B',
    ('POST', '/api/v1/admin/configurations/{configuration_id}/activate'): 'B',
    ('POST', '/api/v1/admin/configurations/{configuration_id}/rollback'): 'B',
    ('POST', '/api/v1/admin/configurations/{configuration_id}/validate'): 'B',
    ('POST', '/api/v1/admin/reanalysis/preview'): 'B',
    ('POST', '/api/v1/admin/reanalysis/run'): 'B',
    ('POST', '/api/v1/exercises/{exercise_id}/attempts'): 'A',
    ('POST', '/api/v1/practice-targets'): 'B',
    ('POST', '/api/v1/practice-targets/{practice_target_id}/exercises'): 'A',
    ('POST', '/api/v1/research/dataset-split'): 'A',
    ('POST', '/api/v1/research/export/preview'): 'A',
    ('POST', '/api/v1/research/export/run'): 'A',
    ('POST', '/api/v1/research/reviews'): 'A',
    ('POST', '/api/v1/revisions'): 'B',
    ('POST', '/api/v1/students/{student_id}/learner-model/preview'): 'A',
    ('POST', '/api/v1/students/{student_id}/learner-model/rebuild'): 'A',
    ('POST', '/api/v1/submissions'): 'A',
    ('POST', '/api/v1/submissions/{submission_id}/analyses'): 'B',
    ('POST', '/api/v1/submissions/{submission_id}/calf/reanalyze'): 'C',
    ('POST', '/api/v1/submissions/{submission_id}/error-annotations/import'): 'C',
    ('POST', '/api/v1/submissions/{submission_id}/pii-review'): 'C',
}

ENDPOINT_UNWRAPPED_REASON: dict[tuple[str, str], str] = {
    ('GET', '/api/v1/admin/algorithms'): 'admin-only registry inspection',
    ('GET', '/api/v1/admin/metrics'): 'admin-only registry inspection',
    ('GET', '/api/v1/calf/analysis-units'): 'registry inspection; future feature',
    ('GET', '/api/v1/calf/metrics/{metric_id}'): 'registry inspection; future feature',
    ('GET', '/api/v1/research/export/{export_id}'): 'export job status; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}'): 'aggregate student read; accessed through other endpoints',
    ('GET', '/api/v1/students/{student_id}/calf-trajectories'): 'CALF trajectories; future feature',
    ('GET', '/api/v1/students/{student_id}/history'): 'learner history read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/learner-model/diagnostic-trajectories'): 'learner-model detail read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/learner-model/history-evidence'): 'learner-model detail read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/learner-model/learning-targets'): 'learner-model detail read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/learner-model/metric-trajectories'): 'learner-model detail read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/learner-model/task-clusters'): 'learner-model detail read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/profile'): 'learner profile read; not part of current Streamlit product',
    ('GET', '/api/v1/students/{student_id}/progress'): 'learner progress read; not part of current Streamlit product',
    ('GET', '/api/v1/submissions/{submission_id}/analysis-units'): 'analysis-unit inspection; future feature',
    ('GET', '/api/v1/submissions/{submission_id}/error-annotations'): 'error-annotation inspection; future feature',
    ('GET', '/api/v1/submissions/{submission_id}/syntactic-units'): 'syntactic-unit inspection; future feature',
    ('GET', '/api/v1/system/version'): 'API/debug inspection',
    ('GET', '/docs'): 'framework API documentation',
    ('GET', '/docs/oauth2-redirect'): 'framework API documentation',
    ('GET', '/openapi.json'): 'framework API documentation',
    ('GET', '/redoc'): 'framework API documentation',
    ('POST', '/api/v1/submissions/{submission_id}/calf/reanalyze'): 'CALF reanalysis action; future feature',
    ('POST', '/api/v1/submissions/{submission_id}/error-annotations/import'): 'error-annotation import; future feature',
    ('POST', '/api/v1/submissions/{submission_id}/pii-review'): 'PII review workflow; not part of current Streamlit product',
}

CLIENT_METHOD_CLASSIFICATION: dict[str, str] = {
    'activate_configuration': 'B',
    'create_configuration': 'B',
    'create_dataset_split': 'A',
    'create_exercise': 'A',
    'create_human_review': 'A',
    'create_practice_target': 'A',
    'create_revision': 'B',
    'get_analyses': 'A',
    'get_calf': 'B',
    'get_calf_constructs': 'B',
    'get_calf_metrics': 'B',
    'get_configurations': 'A',
    'get_dashboard': 'B',
    'get_diagnostic_audit': 'A',
    'get_engagement_traces': 'A',
    'get_exercise_attempts': 'A',
    'get_exercise_instances': 'A',
    'get_journey': 'A',
    'get_learner_model': 'B',
    'get_learner_model_snapshot': 'B',
    'get_learner_model_snapshots': 'B',
    'get_pii_candidates': 'A',
    'get_practice_targets': 'A',
    'get_practice_target_context': 'A',
    'get_registries': 'B',
    'get_revision_analysis': 'B',
    'get_revision_candidates': 'B',
    'get_revision_comparison': 'B',
    'get_revision_group': 'B',
    'get_revision_trajectory': 'B',
    'get_student_revision_candidates': 'A',
    'get_submission': 'A',
    'get_transfer_evidence': 'A',
    'health': 'A',
    'lifecycle_state': 'C',
    'list_human_reviews': 'B',
    'live': 'B',
    'preview_learner_model': 'A',
    'preview_reanalysis': 'B',
    'ready': 'B',
    'reanalyze': 'B',
    'rebuild_learner_model': 'A',
    'research_data_quality': 'A',
    'research_export_history': 'A',
    'research_export_manifest': 'B',
    'research_export_preview': 'A',
    'research_export_run': 'A',
    'research_export_schema': 'B',
    'rollback_configuration': 'B',
    'run_reanalysis': 'B',
    'submit': 'A',
    'submit_linked_revision': 'A',
    'submit_exercise_attempt': 'A',
    'validate_configuration': 'B',
}

CLIENT_METHOD_STATUS: dict[str, str] = {
    'activate_configuration': 'admin configuration action; not in current UI',
    'create_configuration': 'admin configuration action; not in current UI',
    'create_revision': 'revision linking; not in current UI',
    'get_calf': 'CALF submission read; not in current UI',
    'get_calf_constructs': 'CALF registry read; not in current UI',
    'get_calf_metrics': 'CALF registry read; not in current UI',
    'get_dashboard': 'dashboard read; not in current UI',
    'get_learner_model': 'learner-model read; not in current UI',
    'get_learner_model_snapshot': 'learner-model read; not in current UI',
    'get_learner_model_snapshots': 'learner-model read; not in current UI',
    'get_registries': 'admin registry inspection; not in current UI',
    'get_revision_analysis': 'revision detail read; not in current UI',
    'get_revision_candidates': 'revision detail read; not in current UI',
    'get_revision_comparison': 'revision detail read; not in current UI',
    'get_revision_group': 'revision detail read; not in current UI',
    'get_revision_trajectory': 'revision detail read; not in current UI',
    'lifecycle_state': 'convenience helper; not an HTTP wrapper (no endpoint mapping)',
    'list_human_reviews': 'review listing; not in current UI',
    'live': 'lifecycle inspection used by the app shell, not feature modules',
    'preview_reanalysis': 'admin reanalysis preview; not in current UI',
    'ready': 'lifecycle inspection used by the app shell, not feature modules',
    'reanalyze': 'reanalysis action; not in current UI',
    'research_export_manifest': 'manifest read; not in current UI (run response carries the manifest)',
    'research_export_schema': 'export schema inspection; not in current UI',
    'rollback_configuration': 'admin configuration action; not in current UI',
    'run_reanalysis': 'admin reanalysis run; not in current UI',
    'validate_configuration': 'admin configuration action; not in current UI',
}

FEATURE_PORTS: dict[str, str] = {
    'research_calf': 'ResearchCalfApiPort',
    'research_data': 'ResearchDataApiPort',
    'research_evidence': 'ResearchEvidenceApiPort',
    'research_learning_process': 'ResearchLearningProcessApiPort',
    'research_overview': 'ResearchOverviewApiPort',
    'research_system_audit': 'ResearchSystemAuditApiPort',
    'student_feedback': 'StudentFeedbackApiPort',
    'student_home': 'StudentHomeApiPort',
    'student_journey': 'StudentJourneyApiPort',
    'student_practice': 'StudentPracticeApiPort',
    'student_revision': 'StudentRevisionApiPort',
    'student_writing': 'StudentWritingApiPort',
}

PORT_METHODS: dict[str, list[str]] = {
    'ResearchCalfApiPort': [],
    'ResearchDataApiPort': ['create_dataset_split', 'create_human_review', 'get_pii_candidates', 'research_data_quality', 'research_export_history', 'research_export_preview', 'research_export_run'],
    'ResearchEvidenceApiPort': ['get_analyses', 'get_diagnostic_audit', 'get_submission'],
    'ResearchLearningProcessApiPort': ['get_engagement_traces', 'get_journey', 'get_practice_targets', 'get_transfer_evidence'],
    'ResearchOverviewApiPort': ['health', 'research_data_quality'],
    'ResearchSystemAuditApiPort': ['get_configurations', 'get_diagnostic_audit', 'preview_learner_model', 'rebuild_learner_model'],
    'StudentFeedbackApiPort': ['get_student_revision_candidates'],
    'StudentHomeApiPort': ['get_journey', 'get_practice_targets'],
    'StudentJourneyApiPort': ['get_journey'],
    'StudentPracticeApiPort': ['create_exercise', 'create_practice_target', 'get_exercise_attempts', 'get_exercise_instances', 'get_practice_target_context', 'get_practice_targets', 'submit_exercise_attempt'],
    'StudentRevisionApiPort': ['get_practice_targets', 'get_student_revision_candidates', 'get_submission', 'submit_linked_revision'],
    'StudentWritingApiPort': ['get_student_revision_candidates', 'get_submission', 'submit'],
}

CLIENT_ENDPOINT_MAP: dict[str, list[tuple[str, str]]] = {
    'activate_configuration': [('POST', '/api/v1/admin/configurations/{}/activate')],
    'create_configuration': [('POST', '/api/v1/admin/configurations')],
    'create_dataset_split': [('POST', '/api/v1/research/dataset-split')],
    'create_exercise': [('POST', '/api/v1/practice-targets/{}/exercises')],
    'create_human_review': [('POST', '/api/v1/research/reviews')],
    'create_practice_target': [('POST', '/api/v1/practice-targets')],
    'create_revision': [('POST', '/api/v1/revisions')],
    'get_analyses': [('GET', '/api/v1/submissions/{}/analyses')],
    'get_calf': [('GET', '/api/v1/submissions/{}/calf')],
    'get_calf_constructs': [('GET', '/api/v1/calf/constructs')],
    'get_calf_metrics': [('GET', '/api/v1/calf/metrics')],
    'get_configurations': [('GET', '/api/v1/admin/configurations')],
    'get_dashboard': [('GET', '/api/v1/students/{}/dashboard')],
    'get_diagnostic_audit': [('GET', '/api/v1/submissions/{}/diagnostic-audit')],
    'get_engagement_traces': [('GET', '/api/v1/students/{}/engagement-traces')],
    'get_exercise_attempts': [('GET', '/api/v1/exercises/{}/attempts')],
    'get_exercise_instances': [('GET', '/api/v1/practice-targets/{}/exercises')],
    'get_journey': [('GET', '/api/v1/students/{}/journey')],
    'get_learner_model': [('GET', '/api/v1/students/{}/learner-model')],
    'get_learner_model_snapshot': [('GET', '/api/v1/students/{}/learner-model/snapshots/{}')],
    'get_learner_model_snapshots': [('GET', '/api/v1/students/{}/learner-model/snapshots')],
    'get_pii_candidates': [('GET', '/api/v1/submissions/{}/pii-candidates')],
    'get_practice_targets': [('GET', '/api/v1/students/{}/practice-targets')],
    'get_practice_target_context': [('GET', '/api/v1/students/{}/practice-targets/{}/context')],
    'get_registries': [('GET', '/api/v1/admin/registries')],
    'get_revision_analysis': [('GET', '/api/v1/submissions/{}/revision-analysis')],
    'get_revision_candidates': [('GET', '/api/v1/submissions/{}/revision-candidates')],
    'get_revision_comparison': [('GET', '/api/v1/revisions/{}/comparison')],
    'get_revision_group': [('GET', '/api/v1/revisions/{}')],
    'get_revision_trajectory': [('GET', '/api/v1/revisions/{}/trajectory')],
    'get_student_revision_candidates': [('GET', '/api/v1/students/{}/revision-candidates')],
    'get_submission': [('GET', '/api/v1/submissions/{}')],
    'get_transfer_evidence': [('GET', '/api/v1/students/{}/transfer-evidence')],
    'health': [('GET', '/api/v1/system/health')],
    'list_human_reviews': [('GET', '/api/v1/research/reviews')],
    'live': [('GET', '/api/v1/system/live')],
    'preview_learner_model': [('POST', '/api/v1/students/{}/learner-model/preview')],
    'preview_reanalysis': [('POST', '/api/v1/admin/reanalysis/preview')],
    'ready': [('GET', '/api/v1/system/ready')],
    'reanalyze': [('POST', '/api/v1/submissions/{}/analyses')],
    'rebuild_learner_model': [('POST', '/api/v1/students/{}/learner-model/rebuild')],
    'research_data_quality': [('GET', '/api/v1/research/data-quality')],
    'research_export_history': [('GET', '/api/v1/research/export/history')],
    'research_export_manifest': [('GET', '/api/v1/research/export/{}/manifest')],
    'research_export_preview': [('POST', '/api/v1/research/export/preview')],
    'research_export_run': [('POST', '/api/v1/research/export/run')],
    'research_export_schema': [('GET', '/api/v1/research/export/schema')],
    'rollback_configuration': [('POST', '/api/v1/admin/configurations/{}/rollback')],
    'run_reanalysis': [('POST', '/api/v1/admin/reanalysis/run')],
    'submit': [('POST', '/api/v1/submissions')],
    'submit_linked_revision': [('POST', '/api/v1/submissions')],
    'submit_exercise_attempt': [('POST', '/api/v1/exercises/{}/attempts')],
    'validate_configuration': [('POST', '/api/v1/admin/configurations/{}/validate')],
}

FACADE_PRIVATE_HELPER_ALLOWLIST: tuple[str, ...] = (
    "tests/test_v095c_feature_extraction.py",
)
