from __future__ import annotations

from typing import Any, Protocol

from app.core import LearnerProfileSnapshot
from app.models import AnalysisResult, DiagnosisResult, EssaySubmission, HistoryResult, ProviderResult
from app.revision import RevisionGroup, RevisionSnapshot


class StudentRepository(Protocol):
    def get_student(self, student_id: str) -> dict[str, Any] | None: ...


class EssayRepository(Protocol):
    def save_essay(self, submission: EssaySubmission, *, synthetic: bool = False) -> int: ...
    def get_submission_bundle(self, essay_id: int) -> dict[str, Any] | None: ...
    def list_student_submissions(self, student_id: str) -> list[dict[str, Any]]: ...


class MetricRepository(Protocol):
    def save_analysis(self, essay_id: int, analysis: AnalysisResult) -> None: ...
    def save_analysis_run(self, essay_id: int, analysis: AnalysisResult) -> AnalysisResult: ...
    def list_analysis_runs(self, essay_id: int) -> list[dict[str, Any]]: ...


class DiagnosisRepository(Protocol):
    def save_diagnosis(self, essay_id: int, diagnosis: DiagnosisResult) -> None: ...


class FeedbackRepository(Protocol):
    def save_feedback(self, essay_id: int, result: ProviderResult, analysis_version: str) -> None: ...


class ExerciseRepository(Protocol):
    def get_exercises(self, essay_id: int) -> list[dict[str, Any]]: ...


class LearnerHistoryRepository(Protocol):
    def prior_records(self, submission: EssaySubmission) -> list[dict[str, Any]]: ...
    def save_history(self, student_id: str, essay_id: int, history: HistoryResult) -> None: ...
    def list_student_history(self, student_id: str) -> list[dict[str, Any]]: ...


class LearnerProfileRepository(Protocol):
    def get_latest_learner_profile(self, student_id: str) -> dict[str, Any] | None: ...
    def save_learner_profile_snapshot(self, snapshot: LearnerProfileSnapshot) -> LearnerProfileSnapshot: ...
    def list_learner_profile_snapshots(self, student_id: str) -> list[dict[str, Any]]: ...
    def list_longitudinal_records(self, student_id: str) -> list[dict[str, Any]]: ...
    def list_visualization_records(self, student_id: str) -> list[dict[str, Any]]: ...
    def list_history_evidence(self, student_id: str) -> list[dict[str, Any]]: ...


class RevisionRepository(Protocol):
    def get_submission_bundle(self, essay_id: int) -> dict[str, Any] | None: ...
    def get_latest_analysis_run(self, essay_id: int) -> dict[str, Any] | None: ...
    def create_revision_group(self, source_submission_id: int) -> RevisionGroup: ...
    def link_revision(self, source_submission_id: int, target_submission_id: int, revision_group_id: str) -> None: ...
    def get_revision_group(self, revision_group_id: str) -> RevisionGroup | None: ...
    def get_revision_group_for_submission(self, submission_id: int) -> RevisionGroup | None: ...
    def list_revision_candidates(self, submission_id: int) -> list[dict[str, Any]]: ...
    def save_revision_snapshot(self, snapshot: RevisionSnapshot) -> RevisionSnapshot: ...
    def list_revision_snapshots(self, revision_group_id: str) -> list[dict[str, Any]]: ...
    def get_latest_revision_snapshot(self, revision_group_id: str) -> dict[str, Any] | None: ...


class ConfigurationRepository(Protocol):
    def ping(self) -> bool: ...
    def migration_version(self) -> int: ...


class SystemVersionRepository(Protocol):
    def record_versions(self, versions: dict[str, str]) -> None: ...
    def get_system_versions(self) -> dict[str, str]: ...


SubmissionRepositories = (
    StudentRepository | EssayRepository | MetricRepository | DiagnosisRepository
    | FeedbackRepository | ExerciseRepository | LearnerHistoryRepository
    | LearnerProfileRepository | RevisionRepository | ConfigurationRepository | SystemVersionRepository
)
