from __future__ import annotations

from typing import Any, Protocol

from app.revision import RevisionGroup, RevisionSnapshot


class RevisionRepository(Protocol):
    def get_submission_bundle(self, essay_id: int) -> dict[str, Any] | None: ...
    def get_latest_analysis_run(self, essay_id: int) -> dict[str, Any] | None: ...
    def create_revision_group(self, source_submission_id: int) -> RevisionGroup: ...
    def link_revision(self, source_submission_id: int, target_submission_id: int, revision_group_id: str) -> None: ...
    def get_revision_group(self, revision_group_id: str) -> RevisionGroup | None: ...
    def get_revision_group_for_submission(self, submission_id: int) -> RevisionGroup | None: ...
    def list_revision_candidates(self, submission_id: int) -> list[dict[str, Any]]: ...
    def save_revision_snapshot(self, snapshot: RevisionSnapshot) -> RevisionSnapshot: ...
    def list_revision_snapshots(self, revision_group_id: str) -> list[dict[str, Any]]: ...
    def get_latest_revision_snapshot(self, revision_group_id: str) -> dict[str, Any] | None: ...

